server:
  port: 8081

spring:
  liquibase:
    change-log: classpath:db/changelog/db-changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_example
    username: springuser
    password: ThePassword
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    liquibase: DEBUG

#Custom Properties
apache:
  poi:
    version: 4.1.2


